name 'directory'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures directory'
long_description 'Installs/Configures directory'
version '0.1.0'
